# Generated by Django 5.2.7 on 2025-12-01 16:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='profile_pic',
        ),
        migrations.AddField(
            model_name='customuser',
            name='profile_picture',
            field=models.ImageField(blank=True, null=True, upload_to='profile_pics/', verbose_name='Фотография профиля'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='experience',
            field=models.IntegerField(default=0, verbose_name='Опыт работы (лет)'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='group',
            field=models.CharField(blank=True, help_text='Для студентов: A1, A2, B1, B2, C1', max_length=10, null=True, verbose_name='Группа'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='level',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Уровень английского'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='phone',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Телефон'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='specialization',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Специализация'),
        ),
    ]
