# Generated by Django 5.2.7 on 2025-12-01 17:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_remove_customuser_profile_pic_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='experience',
            field=models.IntegerField(blank=True, default=0, verbose_name='Опыт работы (лет)'),
        ),
    ]
