# Generated by Django 5.2.7 on 2025-11-24 23:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GrammarProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Название продукта')),
                ('description', models.TextField(verbose_name='Описание')),
                ('level', models.CharField(choices=[('A1', 'Уровень A1 (Начальный)'), ('A2', 'Уровень A2 (Элементарный)'), ('B1', 'Уровень B1 (Средний)'), ('B2', 'Уровень B2 (Выше среднего)'), ('C1', 'Уровень C1 (Продвинутый)')], max_length=2, verbose_name='Уровень сложности')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Цена')),
            ],
        ),
        migrations.CreateModel(
            name='GrammarOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_name', models.CharField(max_length=100, verbose_name='Имя заказчика')),
                ('customer_email', models.EmailField(max_length=254, verbose_name='Email заказчика')),
                ('customer_phone', models.CharField(max_length=20, verbose_name='Телефон заказчика')),
                ('order_date', models.DateTimeField(auto_now_add=True, verbose_name='Дата заказа')),
                ('notes', models.TextField(blank=True, verbose_name='Дополнительные пожелания')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='grammar.grammarproduct', verbose_name='Продукт')),
            ],
            options={
                'verbose_name': 'Заказ грамматики',
                'verbose_name_plural': 'Заказы грамматики',
            },
        ),
    ]
