# Generated by Django 5.2.8 on 2025-12-12 09:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('grammar', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='GrammarOrder',
        ),
        migrations.DeleteModel(
            name='GrammarProduct',
        ),
    ]
