# Generated by Django 5.2.7 on 2025-11-25 00:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feedback', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='feedback',
            name='subject',
            field=models.CharField(default='Обратная связь', max_length=200, verbose_name='Тема сообщения'),
        ),
    ]
