# Generated by Django 5.2.7 on 2025-11-25 00:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feedback', '0002_feedback_subject'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feedback',
            name='subject',
            field=models.CharField(max_length=200, verbose_name='Тема сообщения'),
        ),
    ]
