# Generated by Django 5.2.7 on 2025-11-25 09:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feedback', '0003_alter_feedback_subject'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='feedback',
            options={'ordering': ['-created_at'], 'verbose_name': 'Обратная связь', 'verbose_name_plural': 'Обратные связи'},
        ),
        migrations.AddField(
            model_name='feedback',
            name='admin_notes',
            field=models.TextField(blank=True, verbose_name='Заметки администратора'),
        ),
        migrations.AddField(
            model_name='feedback',
            name='attach_file',
            field=models.FileField(blank=True, null=True, upload_to='feedback_attachments/', verbose_name='Прикрепить файл'),
        ),
        migrations.AddField(
            model_name='feedback',
            name='feedback_type',
            field=models.CharField(choices=[('general', 'Общий вопрос'), ('technical', 'Техническая проблема'), ('content', 'Вопрос по содержанию'), ('suggestion', 'Предложение по улучшению'), ('complaint', 'Жалоба'), ('other', 'Другое')], default='general', max_length=20, verbose_name='Тип обращения'),
        ),
        migrations.AddField(
            model_name='feedback',
            name='is_processed',
            field=models.BooleanField(default=False, verbose_name='Обработано'),
        ),
        migrations.AddField(
            model_name='feedback',
            name='phone',
            field=models.CharField(blank=True, max_length=20, verbose_name='Телефон'),
        ),
        migrations.AddField(
            model_name='feedback',
            name='priority',
            field=models.CharField(choices=[('low', 'Низкий'), ('medium', 'Средний'), ('high', 'Высокий')], default='medium', max_length=10, verbose_name='Приоритет'),
        ),
        migrations.AddField(
            model_name='feedback',
            name='processed_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Дата обработки'),
        ),
        migrations.AddField(
            model_name='feedback',
            name='satisfaction',
            field=models.IntegerField(blank=True, choices=[(1, '⭐'), (2, '⭐⭐'), (3, '⭐⭐⭐'), (4, '⭐⭐⭐⭐'), (5, '⭐⭐⭐⭐⭐')], null=True, verbose_name='Оценка удовлетворенности'),
        ),
        migrations.AddField(
            model_name='feedback',
            name='subscribe_newsletter',
            field=models.BooleanField(default=False, verbose_name='Подписаться на рассылку'),
        ),
    ]
