# Generated by Django 5.2.7 on 2025-11-25 09:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feedback', '0004_alter_feedback_options_feedback_admin_notes_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feedback',
            name='satisfaction',
            field=models.IntegerField(default=0, help_text='Оценка от 1 до 5 звезд', verbose_name='Оценка удовлетворенности'),
        ),
    ]
