# Generated by Django 5.2.7 on 2025-11-25 09:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feedback', '0005_alter_feedback_satisfaction'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feedback',
            name='attach_file',
            field=models.FileField(blank=True, null=True, upload_to='feedback_attachments/%Y/%m/%d/', verbose_name='Прикрепленный файл'),
        ),
    ]
