# Generated by Django 5.2.7 on 2025-11-25 10:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feedback', '0006_alter_feedback_attach_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='feedback',
            name='how_found_us',
            field=models.CharField(choices=[('search', 'Поисковая система'), ('social', 'Социальные сети'), ('friend', 'Рекомендация друга'), ('ad', 'Рекламная кампания'), ('other', 'Другое')], default='search', max_length=50, verbose_name='Как вы узнали о нас?'),
        ),
        migrations.AddField(
            model_name='feedback',
            name='improvements_needed',
            field=models.TextField(blank=True, help_text='Ваши предложения по улучшению', verbose_name='Что нам нужно улучшить?'),
        ),
        migrations.AddField(
            model_name='feedback',
            name='recommend_likely',
            field=models.IntegerField(default=0, help_text='Оцените вероятность рекомендации от 0 до 10', verbose_name='Вероятность рекомендации'),
        ),
    ]
