# Generated by Django 5.2.7 on 2025-11-25 10:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feedback', '0007_feedback_how_found_us_feedback_improvements_needed_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='feedback',
            name='how_found_us',
        ),
        migrations.RemoveField(
            model_name='feedback',
            name='improvements_needed',
        ),
        migrations.RemoveField(
            model_name='feedback',
            name='recommend_likely',
        ),
        migrations.AddField(
            model_name='feedback',
            name='question1',
            field=models.TextField(blank=True, verbose_name='Что вам больше всего понравилось в нашем сервисе?'),
        ),
        migrations.AddField(
            model_name='feedback',
            name='question2',
            field=models.TextField(blank=True, verbose_name='Что можно улучшить в работе сервиса?'),
        ),
        migrations.AddField(
            model_name='feedback',
            name='question3',
            field=models.TextField(blank=True, verbose_name='Какие функции вы хотели бы видеть в будущем?'),
        ),
        migrations.AddField(
            model_name='feedback',
            name='question4',
            field=models.TextField(blank=True, verbose_name='Насколько легко вам было найти нужную информацию?'),
        ),
        migrations.AddField(
            model_name='feedback',
            name='question5',
            field=models.TextField(blank=True, verbose_name='Ваши дополнительные пожелания и комментарии'),
        ),
    ]
