# Generated by Django 5.2.7 on 2025-11-25 21:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feedback', '0008_remove_feedback_how_found_us_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='feedback',
            name='satisfaction',
        ),
        migrations.AddField(
            model_name='feedback',
            name='auto_satisfaction',
            field=models.IntegerField(default=0, verbose_name='Автоматическая оценка удовлетворенности'),
        ),
    ]
