# Generated by Django 5.2.7 on 2025-12-02 09:34

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feedback', '0009_remove_feedback_satisfaction_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='feedback',
            name='auto_satisfaction',
        ),
        migrations.RemoveField(
            model_name='feedback',
            name='question1',
        ),
        migrations.RemoveField(
            model_name='feedback',
            name='question2',
        ),
        migrations.RemoveField(
            model_name='feedback',
            name='question3',
        ),
        migrations.RemoveField(
            model_name='feedback',
            name='question4',
        ),
        migrations.RemoveField(
            model_name='feedback',
            name='question5',
        ),
        migrations.AddField(
            model_name='feedback',
            name='additional_comments',
            field=models.TextField(blank=True, verbose_name='Дополнительные комментарии'),
        ),
        migrations.AddField(
            model_name='feedback',
            name='average_rating',
            field=models.FloatField(default=0, verbose_name='Средний рейтинг'),
        ),
        migrations.AddField(
            model_name='feedback',
            name='content_rating',
            field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(5)], verbose_name='Оценка качества контента'),
        ),
        migrations.AddField(
            model_name='feedback',
            name='improvements',
            field=models.TextField(blank=True, verbose_name='Что можно улучшить?'),
        ),
        migrations.AddField(
            model_name='feedback',
            name='max_possible_score',
            field=models.IntegerField(default=0, verbose_name='Максимально возможный балл'),
        ),
        migrations.AddField(
            model_name='feedback',
            name='most_liked',
            field=models.TextField(blank=True, verbose_name='Что больше всего понравилось?'),
        ),
        migrations.AddField(
            model_name='feedback',
            name='overall_satisfaction',
            field=models.CharField(blank=True, choices=[('very_satisfied', 'Полностью доволен'), ('satisfied', 'Доволен'), ('neutral', 'Нейтрально'), ('unsatisfied', 'Не доволен'), ('very_unsatisfied', 'Совсем не доволен')], max_length=20, verbose_name='Общая удовлетворенность сервисом'),
        ),
        migrations.AddField(
            model_name='feedback',
            name='site_design_rating',
            field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(5)], verbose_name='Оценка дизайна сайта'),
        ),
        migrations.AddField(
            model_name='feedback',
            name='speed_rating',
            field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(5)], verbose_name='Оценка скорости работы'),
        ),
        migrations.AddField(
            model_name='feedback',
            name='suggestions',
            field=models.TextField(blank=True, verbose_name='Ваши предложения'),
        ),
        migrations.AddField(
            model_name='feedback',
            name='total_score',
            field=models.IntegerField(default=0, verbose_name='Общий балл'),
        ),
        migrations.AddField(
            model_name='feedback',
            name='usability_rating',
            field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(5)], verbose_name='Оценка удобства использования'),
        ),
        migrations.AddField(
            model_name='feedback',
            name='would_recommend',
            field=models.CharField(blank=True, choices=[('definitely', 'Определенно да'), ('probably', 'Вероятно да'), ('not_sure', 'Не уверен'), ('probably_not', 'Вероятно нет'), ('definitely_not', 'Определенно нет')], max_length=20, verbose_name='Порекомендуете ли вы наш сайт друзьям?'),
        ),
        migrations.AlterField(
            model_name='feedback',
            name='feedback_type',
            field=models.CharField(choices=[('general', 'Общий вопрос'), ('technical', 'Техническая проблема'), ('suggestion', 'Предложение по улучшению'), ('other', 'Другое')], default='general', max_length=20, verbose_name='Тип обращения'),
        ),
    ]
