# Generated by Django 5.2.7 on 2025-12-02 10:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feedback', '0010_remove_feedback_auto_satisfaction_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='feedback',
            name='comments_sentiment_score',
            field=models.FloatField(default=0, verbose_name='Оценка тональности комментариев'),
        ),
    ]
