# Generated by Django 5.2.7 on 2025-12-13 06:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('feedback', '0014_feedbacklike'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='feedback',
            name='priority',
        ),
    ]
