# Generated by Django 5.2.7 on 2025-12-08 01:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='courseorder',
            name='completed_modules',
            field=models.ManyToManyField(blank=True, related_name='completed_orders', to='courses.coursemodule', verbose_name='Пройденные модули'),
        ),
    ]
