# Generated by Django 5.2.7 on 2025-12-08 07:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0002_courseorder_completed_modules'),
    ]

    operations = [
        migrations.AddField(
            model_name='courseorder',
            name='cancellation_reason',
            field=models.TextField(blank=True, verbose_name='Причина отмены'),
        ),
    ]
