# Generated by Django 5.2.8 on 2025-12-13 00:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0003_courseorder_cancellation_reason'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='duration_weeks',
        ),
    ]
