# Generated by Django 5.2.7 on 2025-12-14 08:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0004_remove_course_duration_weeks'),
    ]

    operations = [
        migrations.AddField(
            model_name='courseorder',
            name='notes',
            field=models.TextField(blank=True, verbose_name='Комментарии студента при записи'),
        ),
    ]
